export const breadcrumbRoutes = [
  // Main Routes
  { path: "/home", label: "sidebar.home" },
  { path: "/inbox", label: "sidebar.inbox" },
  
  // Accounting Module
  { path: "/accounting", label: "sidebar.accounting" },
  { path: "/accounting/entries", label: "accounting.entries.title" },
  { path: "/accounting/entries/create", label: "accounting.entries.create_new" },
  { path: "/accounting/cash-custody", label: "accounting.cash_custody" },
  { path: "/accounting/receipt-documents", label: "accounting.receipt_documents" },
  { path: "/accounting/payment-documents", label: "accounting.payment_documents" },
  
  // Purchases Module
  { path: "/purchases", label: "sidebar.purchases" },
  { path: "/purchases/suppliers", label: "purchases.suppliers" },
  { path: "/purchases/purchase-requests", label: "purchases.purchase_requests" },
  { path: "/purchases/price-quote-requests", label: "purchases.price_quote_requests" },
  { path: "/purchases/supplier-price-quotes", label: "purchases.supplier_price_quotes" },
  { path: "/purchases/purchase-orders", label: "purchases.purchase_orders" },
  { path: "/purchases/material-receipts", label: "purchases.material_receipts" },
  { path: "/purchases/purchase-invoices", label: "purchases.purchase_invoices" },
  { path: "/purchases/purchase-returns", label: "purchases.purchase_returns" },
  
  // Sales Module
  { path: "/sales", label: "sidebar.sales" },
  { path: "/sales/sales-invoices", label: "sales.sales_invoices" },
  { path: "/sales/work-orders", label: "sales.work_orders" },
  { path: "/sales/price-quotes", label: "sales.price_quotes" },
  { path: "/sales/sales-returns", label: "sales.sales_returns" },
  { path: "/sales/delivery-notes", label: "sales.delivery_notes" },
  { path: "/sales/price-lists", label: "sales.price_lists" },
  { path: "/sales/sales-representatives", label: "sales.sales_representatives" },
  { path: "/sales/customers", label: "sales.customers" },
  { path: "/sales/customers/add", label: "customers.add_customer" },
  { path: "/sales/customers/edit/:id", label: "customers.edit_customer" },
  
  // Competitions Module
  { path: "/competitions", label: "sidebar.competitions" },
  { path: "/competitions/vendor-qualification", label: "competitions.vendor_qualification" },
  { path: "/competitions/vendor-qualification/add", label: "vendor_qualification.add_vendor" },
  { path: "/competitions/vendor-qualification/edit/:id", label: "vendor_qualification.edit_vendor" },
  { path: "/competitions/vendor-notifications", label: "competitions.vendor_notifications" },
  { path: "/competitions/vendor-users", label: "competitions.vendor_users" },
  { path: "/competitions/vendor-certificates", label: "competitions.vendor_certificates" },
  { path: "/competitions/committee-formation", label: "competitions.committee_formation" },
  { path: "/competitions/competition-launch", label: "competitions.competition_launch" },
  { path: "/competitions/offers-inspection", label: "competitions.offers_inspection" },
  { path: "/competitions/receive-offers", label: "competitions.receive_offers" },
  { path: "/competitions/evaluation-criteria", label: "competitions.evaluation_criteria" },
  { path: "/competitions/award", label: "competitions.award" },
  { path: "/competitions/competition-definition", label: "competitions.competition_definition" },
  { path: "/competitions/commitment", label: "competitions.commitment" },
  { path: "/competitions/agreements", label: "competitions.agreements" },
  { path: "/competitions/contract", label: "competitions.contract" },
  { path: "/competitions/financial-claim", label: "competitions.financial_claim" },
  { path: "/competitions/work-order", label: "competitions.work_order" },
  { path: "/competitions/completion-certificate", label: "competitions.completion_certificate" },
  { path: "/competitions/bank-guarantees", label: "competitions.bank_guarantees" },
  
  // Assets Module
  { path: "/assets", label: "sidebar.assets" },
  { path: "/assets/asset-management", label: "assets.asset_management" },
  { path: "/assets/asset-movements", label: "assets.asset_movements" },
  { path: "/assets/maintenance", label: "assets.maintenance" },
  { path: "/assets/asset-value-adjustment", label: "assets.asset_value_adjustment" },
  { path: "/assets/sale-disposal", label: "assets.sale_disposal" },
  
  // Other Modules
  { path: "/hr", label: "sidebar.hr" },
  { path: "/hr/employee-center", label: "hr.employee_center" },
  { path: "/hr/employee-center?tab=new-employee", label: "hr.new_employees" },
  { path: "/hr/employee-center?tab=work-start", label: "hr.work_start_requests" },
  { path: "/hr/employee-center?tab=contract-renewal", label: "hr.contract_renewal" },
  { path: "/hr/employee-center?tab=resignation", label: "hr.resignation_termination" },
  { path: "/hr/employee-center/add", label: "hr.add_employee" },
  { path: "/hr/my-requests", label: "hr.my_requests" },
  { path: "/hr/my-requests/new", label: "hr.work_start_request" },
  { path: "/projects", label: "sidebar.projects" },
  { path: "/strategy", label: "sidebar.strategy" },
  { path: "/strategy/tasks", label: "strategy.task_management" },
  { path: "/strategy/tasks/add", label: "strategy.add_task" },
  { path: "/strategy/strategic-plans", label: "strategy.strategic_plans" },
  { path: "/strategy/plan-tracking", label: "strategy.plan_tracking" },
  { path: "/strategy/projects", label: "strategy.project_management" },
  { path: "/strategy/approvals", label: "strategy.approvals" },
  { path: "/strategy/documents", label: "strategy.document_records" },
  { path: "/strategy/meetings", label: "strategy.meeting_records" },
  
  // Warehouses Module
  { path: "/warehouses", label: "sidebar.warehouses" },
  { path: "/warehouses/inventory-materials", label: "warehouses.inventory_materials" },
  { path: "/warehouses/warehouse-management", label: "warehouses.warehouse_management" },
  { path: "/warehouses/material-spending", label: "warehouses.material_spending" },
  { path: "/warehouses/item-groups", label: "warehouses.item_groups" },
  { path: "/warehouses/inventory-count", label: "warehouses.inventory_count" },
  { path: "/warehouses/reserved-services", label: "warehouses.reserved_services" },
  { path: "/warehouses/opening-balances", label: "warehouses.opening_balances" },
  { path: "/warehouses/warehouse-settings", label: "warehouses.warehouse_settings" },
  
  // Workflow Engine Module
  { path: "/workflow-engine", label: "sidebar.workflow" },
  { path: "/workflow-engine/workflows", label: "workflow_engine.workflows" },
  { path: "/workflow-engine/verification-templates", label: "workflow_engine.verification_templates" },
  { path: "/workflow-engine/verification-templates/add", label: "workflow_engine.add_verification_list" },
  { path: "/workflow-engine/verification-templates/edit/:id", label: "workflow_engine.edit_verification_list" },
  { path: "/workflow-engine/predefined-rules", label: "workflow_engine.predefined_rules" },
  { path: "/workflow", label: "sidebar.workflow" },
  
  // Reports Module
  { path: "/reports", label: "sidebar.reports" },
  { path: "/reports/general-ledger", label: "reports.general_ledger" },
  { path: "/reports/trial-balance", label: "reports.trial_balance" },
  { path: "/reports/financial-position", label: "reports.financial_position" },
  { path: "/reports/income-statement", label: "reports.income_statement" },
  { path: "/reports/trial-balance-movement", label: "reports.trial_balance_movement" },
  
  { path: "/settings", label: "sidebar.settings" },
  { path: "/support", label: "sidebar.support" },
];
