export const breadcrumbRoutes = [
  // Main Routes
  { path: "/home", label: "sidebar.home" },
  { path: "/inbox", label: "sidebar.inbox" },
  
  // Accounting Module
  { path: "/accounting", label: "sidebar.accounting" },
  { path: "/accounting/entries", label: "accounting.entries.title" },
  { path: "/accounting/entries/create", label: "accounting.entries.create_new" },
  { path: "/accounting/cash-custody", label: "accounting.cash_custody" },
  { path: "/accounting/receipt-documents", label: "accounting.receipt_documents" },
  { path: "/accounting/payment-documents", label: "accounting.payment_documents" },
  
  // Purchases Module
  { path: "/purchases", label: "sidebar.purchases" },
  { path: "/purchases/suppliers", label: "purchases.suppliers" },
  { path: "/purchases/purchase-requests", label: "purchases.purchase_requests" },
  { path: "/purchases/price-quote-requests", label: "purchases.price_quote_requests" },
  { path: "/purchases/supplier-price-quotes", label: "purchases.supplier_price_quotes" },
  { path: "/purchases/purchase-orders", label: "purchases.purchase_orders" },
  { path: "/purchases/material-receipts", label: "purchases.material_receipts" },
  { path: "/purchases/purchase-invoices", label: "purchases.purchase_invoices" },
  { path: "/purchases/purchase-returns", label: "purchases.purchase_returns" },
  
  // Sales Module
  { path: "/sales", label: "sidebar.sales" },
  { path: "/sales/sales-invoices", label: "sales.sales_invoices" },
  { path: "/sales/work-orders", label: "sales.work_orders" },
  { path: "/sales/price-quotes", label: "sales.price_quotes" },
  { path: "/sales/sales-returns", label: "sales.sales_returns" },
  { path: "/sales/delivery-notes", label: "sales.delivery_notes" },
  { path: "/sales/price-lists", label: "sales.price_lists" },
  { path: "/sales/sales-representatives", label: "sales.sales_representatives" },
  { path: "/sales/customers", label: "sales.customers" },
  { path: "/sales/customers/add", label: "customers.add_customer" },
  { path: "/sales/customers/edit/:id", label: "customers.edit_customer" },
  
  // Competitions Module
  { path: "/competitions", label: "sidebar.competitions" },
  { path: "/competitions/vendor-qualification", label: "competitions.vendor_qualification" },
  { path: "/competitions/vendor-qualification/add", label: "vendor_qualification.add_vendor" },
  { path: "/competitions/vendor-qualification/edit/:id", label: "vendor_qualification.edit_vendor" },
  { path: "/competitions/vendor-notifications", label: "competitions.vendor_notifications" },
  { path: "/competitions/vendor-users", label: "competitions.vendor_users" },
  { path: "/competitions/vendor-certificates", label: "competitions.vendor_certificates" },
  { path: "/competitions/committee-formation", label: "competitions.committee_formation" },
  { path: "/competitions/competition-launch", label: "competitions.competition_launch" },
  { path: "/competitions/offers-inspection", label: "competitions.offers_inspection" },
  { path: "/competitions/receive-offers", label: "competitions.receive_offers" },
  { path: "/competitions/evaluation-criteria", label: "competitions.evaluation_criteria" },
  { path: "/competitions/award", label: "competitions.award" },
  { path: "/competitions/competition-definition", label: "competitions.competition_definition" },
  { path: "/competitions/commitment", label: "competitions.commitment" },
  { path: "/competitions/agreements", label: "competitions.agreements" },
  { path: "/competitions/contract", label: "competitions.contract" },
  { path: "/competitions/financial-claim", label: "competitions.financial_claim" },
  { path: "/competitions/work-order", label: "competitions.work_order" },
  { path: "/competitions/completion-certificate", label: "competitions.completion_certificate" },
  { path: "/competitions/bank-guarantees", label: "competitions.bank_guarantees" },
  
  // Other Modules
  { path: "/assets", label: "sidebar.assets" },
  { path: "/hr", label: "sidebar.hr" },
  { path: "/projects", label: "sidebar.projects" },
  { path: "/strategy", label: "sidebar.strategy" },
  { path: "/warehouses", label: "sidebar.warehouses" },
  { path: "/workflow", label: "sidebar.workflow" },
  { path: "/reports", label: "sidebar.reports" },
  { path: "/settings", label: "sidebar.settings" },
  { path: "/support", label: "sidebar.support" },
];
