export const breadcrumbRoutes = [
  // Main Routes
  { path: "/home", label: "sidebar.home" },
  { path: "/inbox", label: "sidebar.inbox" },
  
  // Accounting Module
  { path: "/accounting", label: "sidebar.accounting" },
  { path: "/accounting/entries", label: "accounting.entries.title" },
  { path: "/accounting/entries/create", label: "accounting.entries.create_new" },
  { path: "/accounting/cash-custody", label: "accounting.cash_custody" },
  { path: "/accounting/cash-custody/create", label: "accounting.cash_custody_create" },
  { path: "/accounting/receipt-vouchers", label: "accounting.receipt_documents" },
  { path: "/accounting/receipt-vouchers/create", label: "accounting.receipt_vouchers_create" },
  { path: "/accounting/payment-vouchers", label: "accounting.payment_documents" },
  { path: "/accounting/payment-vouchers/create", label: "accounting.payment_vouchers_create" },
  
  // Purchases Module
  { path: "/purchases", label: "sidebar.purchases" },
  { path: "/purchases/suppliers", label: "purchases.suppliers" },
  { path: "/purchases/material-requests", label: "purchases.purchase_requests" },
  { path: "/purchases/material-requests/create", label: "purchases.create_material_request" },
  { path: "/purchases/purchase-requests", label: "purchases.purchase_requests" },
  { path: "/purchases/price-quote-requests", label: "purchases.price_quote_requests" },
  { path: "/purchases/supplier-price-quotes", label: "purchases.supplier_price_quotes" },
  { path: "/purchases/purchase-orders", label: "purchases.purchase_orders" },
  { path: "/purchases/material-receipts", label: "purchases.material_receipts" },
  { path: "/purchases/purchase-invoices", label: "purchases.purchase_invoices" },
  { path: "/purchases/purchase-returns", label: "purchases.purchase_returns" },
  
  // Sales Module
  { path: "/sales", label: "sidebar.sales" },
  { path: "/sales/sales-invoices", label: "sales.sales_invoices" },
  { path: "/sales/work-orders", label: "sales.work_orders" },
  { path: "/sales/price-quotes", label: "sales.price_quotes" },
  { path: "/sales/sales-returns", label: "sales.sales_returns" },
  { path: "/sales/delivery-notes", label: "sales.delivery_notes" },
  { path: "/sales/price-lists", label: "sales.price_lists" },
  { path: "/sales/sales-representatives", label: "sales.sales_representatives" },
  { path: "/sales/customers", label: "sales.customers" },
  { path: "/sales/customers/add", label: "customers.add_customer" },
  { path: "/sales/customers/edit/:id", label: "customers.edit_customer" },
  { path: "/sales/price-quotes/add", label: "price_quotes.add_price_quote" },
  { path: "/sales/price-quotes/edit/:id", label: "price_quotes.edit_price_quote" },
  { path: "/sales/work-orders/add", label: "work_orders.add_work_order" },
  { path: "/sales/work-orders/edit/:id", label: "work_orders.edit_work_order" },
  { path: "/sales/sales-invoices/add", label: "sales_invoices.add_sales_invoice" },
  { path: "/sales/sales-invoices/edit/:id", label: "sales_invoices.edit_sales_invoice" },
  { path: "/sales/delivery-notes/add", label: "delivery_notes.add_delivery_note" },
  { path: "/sales/delivery-notes/edit/:id", label: "delivery_notes.edit_delivery_note" },
  { path: "/sales/price-lists/add", label: "price_lists.add_price_list" },
  { path: "/sales/price-lists/edit/:id", label: "price_lists.edit_price_list" },
  { path: "/sales/sales-representatives", label: "sales.sales_representatives" },
  
  // Competitions Module
  { path: "/competitions", label: "sidebar.competitions" },
  { path: "/competitions/vendor-qualification", label: "competitions.vendor_qualification.title" },
  { path: "/competitions/vendor-qualification/add", label: "competitions.vendor_qualification.add_new" },
  { path: "/competitions/vendor-qualification/edit/:id", label: "competitions.vendor_qualification.add_new" },
  { path: "/competitions/vendor-notifications", label: "competitions.vendor_notifications.title" },
  { path: "/competitions/vendor-notifications/add", label: "competitions.vendor_notifications.add_new" },
  { path: "/competitions/vendor-notifications/edit/:id", label: "competitions.vendor_notifications.add_new" },
  { path: "/competitions/vendor-users", label: "competitions.vendor_users.title" },
  { path: "/competitions/vendor-users/add", label: "competitions.vendor_users.add_new" },
  { path: "/competitions/vendor-users/edit/:id", label: "competitions.vendor_users.add_new" },
  { path: "/competitions/vendor-certificates", label: "competitions.vendor_certificates" },
  { path: "/competitions/committee-formation", label: "competitions.committee_formation.title" },
  { path: "/competitions/committee-formation/add", label: "competitions.committee_formation.add_new" },
  { path: "/competitions/committee-formation/edit/:id", label: "competitions.committee_formation.add_new" },
  { path: "/competitions/evaluation-criteria", label: "competitions.evaluation_criteria.title" },
  { path: "/competitions/evaluation-criteria/add", label: "competitions.evaluation_criteria.add_new" },
  { path: "/competitions/evaluation-criteria/edit/:id", label: "competitions.evaluation_criteria.add_new" },
  { path: "/competitions/competition-launch", label: "competitions.competition_launch.title" },
  { path: "/competitions/competition-launch/add", label: "competitions.competition_launch.add_new" },
  { path: "/competitions/competition-launch/edit/:id", label: "competitions.competition_launch.add_new" },
  { path: "/competitions/competition-extension", label: "competitions.competition_extension.title" },
  { path: "/competitions/competition-extension/add", label: "competitions.competition_extension.add_new" },
  { path: "/competitions/competition-extension/edit/:id", label: "competitions.competition_extension.add_new" },
  { path: "/competitions/receive-offers", label: "competitions.receive_offers.title" },
  { path: "/competitions/receive-offers/add", label: "competitions.receive_offers.add_new" },
  { path: "/competitions/receive-offers/edit/:id", label: "competitions.receive_offers.add_new" },
  { path: "/competitions/open-offers", label: "competitions.open_offers.title" },
  { path: "/competitions/open-offers/add", label: "competitions.open_offers.add_new" },
  { path: "/competitions/open-offers/edit/:id", label: "competitions.open_offers.add_new" },
  { path: "/competitions/offers-inspection", label: "competitions.offers_inspection.title" },
  { path: "/competitions/offers-inspection/add", label: "competitions.offers_inspection.add_new" },
  { path: "/competitions/offers-inspection/edit/:id", label: "competitions.offers_inspection.add_new" },
  { path: "/competitions/award", label: "competitions.award.title" },
  { path: "/competitions/award/add", label: "competitions.award.add_new" },
  { path: "/competitions/award/edit/:id", label: "competitions.award.add_new" },
  { path: "/competitions/award-confirmation", label: "competitions.award_confirmation.title" },
  { path: "/competitions/award-confirmation/add", label: "competitions.award_confirmation.add_new" },
  { path: "/competitions/award-confirmation/edit/:id", label: "competitions.award_confirmation.add_new" },
  { path: "/competitions/agreements", label: "competitions.agreements.title" },
  { path: "/competitions/agreements/add", label: "competitions.agreements.add_new" },
  { path: "/competitions/agreements/edit/:id", label: "competitions.agreements.add_new" },
  { path: "/competitions/work-order", label: "competitions.work_order.title" },
  { path: "/competitions/work-order/add", label: "competitions.work_order.add_new" },
  { path: "/competitions/work-order/edit/:id", label: "competitions.work_order.add_new" },
  { path: "/competitions/contract", label: "competitions.contract.title" },
  { path: "/competitions/contract/add", label: "competitions.contract.add_new" },
  { path: "/competitions/contract/edit/:id", label: "competitions.contract.add_new" },
  { path: "/competitions/financial-claim", label: "competitions.financial_claim.title" },
  { path: "/competitions/financial-claim/add", label: "competitions.financial_claim.add_new" },
  { path: "/competitions/financial-claim/edit/:id", label: "competitions.financial_claim.add_new" },
  { path: "/competitions/completion-certificate", label: "competitions.completion_certificate.title" },
  { path: "/competitions/completion-certificate/add", label: "competitions.completion_certificate.add_new" },
  { path: "/competitions/completion-certificate/edit/:id", label: "competitions.completion_certificate.add_new" },
  { path: "/competitions/bank-guarantees", label: "competitions.bank_guarantees.title" },
  { path: "/competitions/bank-guarantees/add", label: "competitions.bank_guarantees.add_new" },
  { path: "/competitions/bank-guarantees/edit/:id", label: "competitions.bank_guarantees.add_new" },
  { path: "/competitions/competition-definition", label: "competitions.competition_definition" },
  { path: "/competitions/bank-guarantees", label: "competitions.bank_guarantees" },
  
  // Assets Module
  { path: "/assets", label: "sidebar.assets" },
  { path: "/assets/asset-management", label: "assets.asset_management" },
  { path: "/assets/asset-management/add", label: "assets.add_asset_form.title" },
  { path: "/assets/asset-management/:id", label: "assets.asset_detail" },
  { path: "/assets/asset-movements", label: "assets.asset_movements.title" },
  { path: "/assets/asset-movements/add", label: "assets.asset_movements.add_new" },
  { path: "/assets/asset-movements/add/asset-detail/:id", label: "assets.asset_detail" },
  { path: "/assets/asset-movements/:id", label: "assets.asset_movements.edit_movement" },
  { path: "/assets/maintenance", label: "assets.maintenance" },
  { path: "/assets/asset-value-adjustment", label: "assets.asset_value_adjustment" },
  { path: "/assets/sale-disposal", label: "assets.sale_disposal" },
  
  // Other Modules
  { path: "/hr", label: "sidebar.hr" },
  { path: "/hr/employee-center", label: "hr.employee_center" },
  { path: "/hr/employee-center?tab=new-employee", label: "hr.new_employees" },
  { path: "/hr/employee-center?tab=work-start", label: "hr.work_start_requests" },
  { path: "/hr/employee-center?tab=contract-renewal", label: "hr.contract_renewal" },
  { path: "/hr/employee-center?tab=resignation", label: "hr.resignation_termination" },
  { path: "/hr/employee-center/add", label: "hr.add_employee" },
  { path: "/hr/leaves-attendance", label: "hr.leaves_attendance" },
  { path: "/hr/leaves-attendance/new", label: "hr.leave_request" },
  { path: "/hr/remote-work", label: "hr.remote_work" },
  { path: "/hr/salaries-rewards", label: "hr.salaries_rewards" },
  { path: "/hr/salaries-rewards/new", label: "hr.new_salary_payroll" },
  { path: "/hr/salaries-rewards/:id", label: "hr.salary_payroll_details" },
  { path: "/hr/salaries-rewards/advance/new", label: "hr.new_advance_request" },
  { path: "/hr/salaries-rewards/promotion/new", label: "hr.new_promotion_request" },
  { path: "/hr/performance-development", label: "hr.performance_development" },
  { path: "/hr/performance-development/add-evaluation", label: "hr.add_evaluation" },
  { path: "/hr/communication-library", label: "hr.communication_library" },
  { path: "/hr/communication-library/new-announcement", label: "hr.new_announcement" },
  { path: "/hr/recruitment", label: "hr.recruitment" },
  { path: "/hr/recruitment/new", label: "hr.new_recruitment_request" },
  { path: "/hr/alerts-requests", label: "hr.alerts_requests_center" },
  { path: "/hr/alerts-requests/new", label: "hr.add_alerts" },
  { path: "/hr/my-requests", label: "hr.my_requests" },
  { path: "/hr/my-requests/new", label: "hr.work_start_request" },
  { path: "/projects", label: "sidebar.projects" },
  { path: "/strategy", label: "sidebar.strategy" },
  { path: "/strategy/tasks", label: "strategy.task_management" },
  { path: "/strategy/tasks/add", label: "strategy.add_task" },
  { path: "/strategy/meetings", label: "strategy.meeting_records" },
  { path: "/strategy/meetings/new", label: "strategy.new_meeting" },
  { path: "/strategy/documents", label: "strategy.document_records" },
  { path: "/strategy/documents/new", label: "strategy.new_document" },
  { path: "/strategy/plan-tracking", label: "strategy.plan_tracking" },
  { path: "/strategy/strategic-plans", label: "strategy.strategic_plans" },
  { path: "/strategy/strategic-plans/new", label: "strategy.new_strategic_plan" },
  { path: "/strategy/strategic-plans/:id", label: "strategy.strategic_plan_details" },
  { path: "/strategy/projects", label: "strategy.project_management" },
  { path: "/strategy/approvals", label: "strategy.approvals" },
  
  // Warehouses Module
  { path: "/warehouses", label: "sidebar.warehouses" },
  { path: "/warehouses/inventory-materials", label: "warehouses.inventory_materials" },
  { path: "/warehouses/warehouse-management", label: "warehouses.warehouse_management" },
  { path: "/warehouses/material-spending", label: "warehouses.material_spending" },
  { path: "/warehouses/item-groups", label: "warehouses.item_groups" },
  { path: "/warehouses/inventory-count", label: "warehouses.inventory_count" },
  { path: "/warehouses/inventory-count/add", label: "warehouses.add_inventory_count" },
  { path: "/warehouses/inventory-count/edit/:id", label: "warehouses.edit_inventory_count" },
  { path: "/warehouses/reserved-services", label: "warehouses.reserved_services" },
  { path: "/warehouses/opening-balances", label: "warehouses.opening_balances" },
  { path: "/warehouses/warehouse-settings", label: "warehouses.warehouse_settings" },
  
  // Workflow Engine Module
  { path: "/workflow-engine", label: "sidebar.workflow" },
  { path: "/workflow-engine/workflows", label: "workflow_engine.workflows" },
  { path: "/workflow-engine/workflows/add", label: "workflow_engine.add_workflow" },
  { path: "/workflow-engine/workflows/edit/:id", label: "workflow_engine.edit_workflow" },
  { path: "/workflow-engine/verification-templates", label: "workflow_engine.verification_templates" },
  { path: "/workflow-engine/verification-templates/add", label: "workflow_engine.add_verification_list" },
  { path: "/workflow-engine/verification-templates/edit/:id", label: "workflow_engine.edit_verification_list" },
  { path: "/workflow-engine/predefined-rules", label: "workflow_engine.predefined_rules" },
  { path: "/workflow", label: "sidebar.workflow" },
  
  // Reports Module
  { path: "/reports", label: "sidebar.reports" },
  { path: "/reports/accounting", label: "sidebar.accounting" },
  { path: "/reports/accounting/general-ledger", label: "reports.accounting.general_ledger" },
  { path: "/reports/accounting/trial-balance", label: "reports.accounting.trial_balance" },
  { path: "/reports/accounting/financial-position", label: "reports.accounting.financial_position" },
  { path: "/reports/accounting/income-statement", label: "reports.accounting.income_statement" },
  { path: "/reports/accounting/trial-balance-movement", label: "reports.accounting.trial_balance_movement" },
  
  { path: "/reports/sales", label: "sidebar.sales" },
  { path: "/reports/sales/representatives-commission", label: "reports.sales.representatives_commission" },
  { path: "/reports/sales/inactive-customers", label: "reports.sales.inactive_customers" },
  { path: "/reports/sales/customer-acquisition", label: "reports.sales.customer_acquisition" },
  { path: "/reports/sales/customer-aging", label: "reports.sales.customer_aging" },
  { path: "/reports/sales/sales-analysis", label: "reports.sales.sales_analysis" },
  
  { path: "/settings", label: "sidebar.settings" },
  { path: "/settings/accounting", label: "sidebar.accounting" },
  { path: "/settings/accounting/company", label: "settings.accounting.company" },
  { path: "/settings/accounting/chart-of-accounts", label: "settings.accounting.chart_of_accounts" },
  { path: "/settings/accounting/account-settings", label: "settings.accounting.account_settings" },
  { path: "/settings/accounting/currencies", label: "settings.accounting.currencies" },
  { path: "/settings/accounting/tax-settings", label: "settings.accounting.tax_settings" },
  { path: "/settings/accounting/fiscal-year", label: "settings.accounting.fiscal_year" },
  { path: "/settings/accounting/accounting-periods", label: "settings.accounting.accounting_periods" },
  { path: "/settings/accounting/payment-methods", label: "settings.accounting.payment_methods" },
  { path: "/settings/accounting/terms-conditions", label: "settings.accounting.terms_conditions" },
  { path: "/settings/accounting/cost-centers", label: "settings.accounting.cost_centers" },
  { path: "/settings/accounting/budget", label: "settings.accounting.budget" },
  { path: "/settings/accounting/budget/create", label: "budget.create_new" },
  { path: "/settings/accounting/budget/edit/:id", label: "budget.edit" },
  { path: "/settings/sales", label: "sidebar.sales" },
  { path: "/settings/sales/sales-settings", label: "settings.sales.sales_settings" },
  { path: "/settings/sales/terms-template", label: "settings.sales.terms_template" },
  { path: "/support", label: "sidebar.support" },
];
