export const breadcrumbRoutes = [
  { path: "/admin", label: "pages.dashboard" },
  { path: "/admin/brands", label: "pages.brands" },
  { path: "/admin/branches", label: "pages.branches" },
  { path: "/admin/brands/new", label: "pages.brands.new" },
  { path: "/admin/brands/new/:slug", label: "pages.brands.edit" },
  { path: "/admin/users", label: "pages.users" },
  { path: "/admin/users/:id", label: "pages.users" },
  { path: "/admin/settings", label: "pages.settings.settings" },
  { path: "/admin/customers", label: "pages.customers" },
  { path: "/admin/customers/:slug", label: "pages.customerDetails" },
  { path: "/admin/customers/:slug/rewards", label: "pages.customers.rewards" },
  { path: "/admin/customers/:slug/messages", label: "pages.customers.messages" },
  {
    path: "/admin/brands/categories",
    label: "pages.categoriesPage.categories",
  },
  { path: "/admin/cards", label: "pages.cardsPage.cards" },
  { path: "/admin/cards/:slug", label: "pages.cardsPage.editCard" },
  { path: "/admin/rewards", label: "pages.rewardsPage.rewards" },
  { path: "/admin/challenges", label: "pages.challengesPage.challenges" },
  { path: "/admin/messaging", label: "pages.messagingPage.messaging" },
  { path: "/admin/messaging/:slug", label: null },
  { path: "/admin/brand-managers", label: "pages.brandManagers" },
  { path: "/admin/brand-users", label: "pages.brandUsers" },
  { path: "/admin/offers", label: "pages.offers" },
  { path: "/admin/customer-experience", label: "pages.customersexperience" },
  { path: "/admin/content-mgmt", label: "pages.contentMgmt" },
  { path: "/admin/content-mgmt/content-mgmt-form", label: "common.createContent" },
  { path: "/admin/content-mgmt/content-mgmt-form/:id", label: "common.updateContent" },
  { path: "/admin/dashboard", label: "pages.dashboard" },
  { path: "/admin/admin-users", label: "pages.adminUsers" },
  { path: "/admin/permissions", label: "pages.permissions" },
];
